# Header

menu:
  ä¸»é¡µ: /
  ç›¸å†Œ: /photos

# SubNav
subnav:
  github: "https://github.com/y19941115mx"
  # weibo: "http://weibo.com/litten225"
  # rss: /atom.xml
  #psn: "#"
  #zhihu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "mailto:1960892068@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# æ˜¯å¦éœ€è¦ä¿®æ”¹ root è·¯å¾„
# å¦‚æœæ‚¨çš„ç½‘ç«™å­˜æ”¾åœ¨å­ç›®å½•ä¸­ï¼Œä¾‹å¦‚ http://yoursite.com/blogï¼Œ
# è¯·å°†æ‚¨çš„ url è®¾ä¸º http://yoursite.com/blog å¹¶æŠŠ root è®¾ä¸º /blog/ã€‚
root: 

# Content
excerpt_link: 'more'
show_all_link: 'å±•å¼€å…¨æ–‡'
fancybox: true
mathjax: false

# æ‰“èµ
# æ‰“èµtypeè®¾å®šï¼š0-å…³é—­æ‰“èµï¼› 1-æ–‡ç« å¯¹åº”çš„mdæ–‡ä»¶é‡Œæœ‰reward:trueå±æ€§ï¼Œæ‰æœ‰æ‰“èµï¼› 2-æ‰€æœ‰æ–‡ç« å‡æœ‰æ‰“èµ
reward_type: 2
reward_wording: 'æ‰«ç  åŠ å¥½å‹ğŸ˜ˆ'
# alipay: /assets/img/alipay.jpg
weixin: /assets/img/weixin.jpg

# ç›®å½•
# ç›®å½•è®¾å®šï¼š0-ä¸æ˜¾ç¤ºç›®å½•ï¼› 1-æ–‡ç« å¯¹åº”çš„mdæ–‡ä»¶é‡Œæœ‰toc:trueå±æ€§ï¼Œæ‰æœ‰ç›®å½•ï¼› 2-æ‰€æœ‰æ–‡ç« å‡æ˜¾ç¤ºç›®å½•
toc: 1
# æ ¹æ®è‡ªå·±çš„ä¹ æƒ¯æ¥è®¾ç½®ï¼Œå¦‚æœä½ çš„ç›®å½•æ ‡é¢˜ä¹ æƒ¯æœ‰æ ‡å·ï¼Œç½®ä¸ºtrueå³å¯éšè—hexoé‡å¤çš„åºå·ï¼›å¦åˆ™ç½®ä¸ºfalse
toc_hide_index: true
# ç›®å½•ä¸ºç©ºæ—¶çš„æç¤º
toc_empty_wording: 'ç›®å½•ï¼Œä¸å­˜åœ¨çš„â€¦'

# æ˜¯å¦æœ‰å¿«é€Ÿå›åˆ°é¡¶éƒ¨çš„æŒ‰é’®
top: true

# æ˜¯å¦åœ¨æ–°çª—å£æ‰“å¼€é“¾æ¥
open_in_new: true

# Miscellaneous
baidu_analytics: false
google_analytics: false
favicon: /assets/img/favicon.ico

#ä½ çš„å¤´åƒurl
avatar: /assets/blogImg/profile.png

#æ˜¯å¦å¼€å¯åˆ†äº«
share_jia: true


mobile:
  social: true

#è¯„è®ºï¼š1ã€å¤šè¯´ï¼›2ã€ç½‘æ˜“äº‘è·Ÿå¸–ï¼›3ã€ç•…è¨€ï¼›4ã€Disqus ä¸éœ€è¦ä½¿ç”¨æŸé¡¹ï¼Œç›´æ¥è®¾ç½®å€¼ä¸ºfalseï¼Œæˆ–æ³¨é‡Šæ‰
#è¯·å‚è€ƒwikiï¼š

#1ã€å¤šè¯´
#duoshuo: "litten-hexo"

#2ã€ç½‘æ˜“äº‘è·Ÿå¸–
#wangyiyun: '2dba06fbf8d24c13915ea6c6aa7183b1'

#3ã€ç•…è¨€
# changyan_appid: 'cysX3aGWt'
# changyan_conf: 'prod_1dcda447175aada96edcdb7e412338fa'
# å¿…åŠ›
livere: 'MTAyMC8zOTQ1MC8xNTk3Nw=='

#6ã€gitalkè¯„è®º
gitalk:
  enable:  true
  githubID:  y19941115mx
  repo:  'gittalk'
  ClientID:  '389b7c12f6ae27554333'
  ClientSecret:  '0a688246a34819bf5bdb70d8e8b6924e8844b48c'
  adminUser:  y19941115mx
  perPage: 15
  distractionFreeMode: true


#4ã€Disqus åœ¨hexoæ ¹ç›®å½•çš„configé‡Œä¹Ÿæœ‰disqus_shortnameå­—æ®µï¼Œä¼˜å…ˆä½¿ç”¨yiliaçš„
disqus: false

# æ ·å¼å®šåˆ¶ - ä¸€èˆ¬ä¸éœ€è¦ä¿®æ”¹ï¼Œé™¤éæœ‰å¾ˆå¼ºçš„å®šåˆ¶æ¬²æœ›â€¦
style:
  # å¤´åƒä¸Šé¢çš„èƒŒæ™¯é¢œè‰²
  header: '#4d4d4d'
  # å³æ»‘æ¿å—èƒŒæ™¯
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# sliderçš„è®¾ç½®
slider:
  # æ˜¯å¦é»˜è®¤å±•å¼€tagsæ¿å—
  showTags: false

# å¦‚ä¸éœ€è¦ï¼Œå°†è¯¥é¡¹ç½®ä¸ºfalse
# æ¯”å¦‚
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: 'æ‰€æœ‰æ–‡ç« '
  friends: false
  aboutme: 'å…³äºæˆ‘'

friends:
  å‹æƒ…é“¾æ¥1: http://localhost:4000/
  å‹æƒ…é“¾æ¥2: http://localhost:4000/
  å‹æƒ…é“¾æ¥3: http://localhost:4000/
  å‹æƒ…é“¾æ¥4: http://localhost:4000/
  å‹æƒ…é“¾æ¥5: http://localhost:4000/
  å‹æƒ…é“¾æ¥6: http://localhost:4000/

aboutme: å–è¿‡æœ€çƒˆçš„é…’ï¼Œ<br/>ä¹Ÿæ”¾è¿‡ä¸è¯¥æ”¾çš„æ‰‹ <br/><br/> ä»å‰ä¸ä¼šå›å¤´ï¼Œ<br/>å¾€åä¸ä¼šå°†å°±